### ISSUE TITLE
Initiative Tracker

### ISSUE THREAD

**Issue by Ernaldis** [Ernaldis/DM-Aid#4]
============
DM Aid
----------
- [ ] Roll initiative for NPCs
- [ ] Enter initiatives for PCs
- [ ] Track HP for NPCs
